unzip ./Bellande_Browser_Application-linux-x64/Bellande_Browser_Application.zip
unzip ./Bellande_Browser_Application-mac-x64/Bellande_Browser_Application.app/Contents/MacOS/Bellande_Browser_Application.zip
